export const SEARCH_INVOICE = 'SEARCH_INVOICE';
export const SEARCH_INVOICE_SUCCESS_FOUND = 'SEARCH_INVOICE_SUCCESS_FIND';
export const SEARCH_INVOICE_FAILURE_FOUND = 'SEARCH_INVOICE_FAILURE_FOUND';
export const SEARCH_INVOICE_FAILURE = 'SEARCH_INVOICE_FAILURE';
